// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBls63CNfcMUk34kmlYiZYB5vz5ClFVgk',
    appId: '1:262681398698:web:ac7909194bcc08e67eafd3',
    messagingSenderId: '262681398698',
    projectId: 'household-groceries',
    authDomain: 'household-groceries.firebaseapp.com',
    storageBucket: 'household-groceries.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-Wy9G9O_sA2QnCRDgGH6QzdAJgjxeIM',
    appId: '1:262681398698:android:0f3f5232403ceda77eafd3',
    messagingSenderId: '262681398698',
    projectId: 'household-groceries',
    storageBucket: 'household-groceries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChq788flSQKtWObkTut7DT7dYmeyNjBNY',
    appId: '1:262681398698:ios:835c7fb4d216d34b7eafd3',
    messagingSenderId: '262681398698',
    projectId: 'household-groceries',
    storageBucket: 'household-groceries.firebasestorage.app',
    iosBundleId: 'com.example.householdGroceries',
  );
}
